### ISSUE TITLE
Rename GetMe Method

### ISSUE THREAD

**Issue by vMaroon** [TekClinic/Patients-MicroService#1]
This should be a one time type issue since initial code wasnt pushed in through a PR.

The method [GetMe](https://github.com/TekClinic/Patients-MicroService/blob/e89e009a85b3c82666210b55005e4967e80fa334/patients_service.proto#L9) of Patients-Service should be renamed.

First, all method declarations and function implementations should be documented - proper documentation should follow [Go Doc Comments](https://tip.golang.org/doc/comment), but I'll accept short and clear freestyle docs as well.

`GetMe` is not acceptable because it is not precise. Pls rename it, through a PR.

**Comment by Whitomtit** [comment]
This method may be deleted at all, since we've defined that patients aren't users of the system. It was useful only for demonstration purpose.
